### ISSUE TITLE
Create MVVM architecture without get_it

### ISSUE THREAD

**Issue by deandreamatias** [madhukesh048/Flutter-MVVM-VS-Code-extension-Pack#10]
I really like create a MVVM architecture with full Provider to state management and injection dependency, without get_it.
Like [this post](https://www.filledstacks.com/post/flutter-provider-v3-architecture/) from FilledStacks

**Comment by scullabyte** [comment]
Thanks for the great extension. Just so I'm clear.. In the current implementation get-it is used for dependency injection of services and Provider is used for value/state management, right?

Say you were to have a value from a stream sent from a database into the ProviderInjector.. Would you load then load that into the ViewModel on initiation or onModelReady?

```dart
  Widget build(BuildContext context) {

	Thing thing = Provider<Thing>.of(context) 

	***HERE?***
    HomeViewModel viewModel = HomeViewModel(thing: thing);
    return ViewModelProvider<HomeViewModel>.withConsumer(
      viewModel: viewModel,
      onModelReady: (viewModel) {
		***OR HERE?***
		viewModel.thing = thing;
        // Do something once your viewModel is initialized
      },

```
