### ISSUE TITLE
Migrate from provider_architecture to Stacked #

### ISSUE THREAD

**Issue by devchenli** [madhukesh048/Flutter-MVVM-VS-Code-extension-Pack#14]
Provider Architecture - Deprecated on 21 April 2020.
V2 of this package is renamed to Stacked .
Hope It can Migrate from provider_architecture to Stacked.
thanks.

**Comment by madhukesh048** [comment]
Hey, here is updated one with stacked package. Please check 
https://marketplace.visualstudio.com/items?itemName=digiMoGo.flutter-stacked-architecture-generator
