### ISSUE TITLE
Updated provider dependency to pubspec.yaml

### ISSUE THREAD

**Issue by Luckey-Elijah** [madhukesh048/Flutter-MVVM-VS-Code-extension-Pack#8]
Currently the `pubspec.yaml` pushes this `provider` dependency at versions `3.2.x` and above.

```
provider: ^3.2.0
```

I would like to have an update to `provider` for `4.x.x` versions as follows.

```
provider: ^4.0.0
```

Certainly not a huge deal, but may provide to be useful for some users that are unaware of the newer version.

**Comment by lcsvcn** [comment]
I solved this in PR #11 

I am just waiting for @madhukesh048 to do a code review and merge.
